# Base configs
baseurl: "https://=AmauryOrtega.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-XXXXXXXX-X"

# UI configs
title: "Photography by Amaury Ortega"
subtitle: "See the 10Y in just a few scenes"
author: "Amaury Ortega"
header:
 title: "Photography"
 subtitle: "by Amaury Ortega"
footer:
 name: "Hey there, my name is AMA"
 bio: "I am an artist and a tech nerd from the same planet as you. Love making teeny tiny things to solve huge and tiny problems."
 github: ";)"
web_design: "AMA"
social_urls:
  twitter: "https://www.twitter.com/amauryortega_"
  instagram: "https://www.instagram.com/uryama.art"
  dribbble: "https://dribbble.com/AmauryOrtega"
  linkedin: "https://in.linkedin.com/in/amaury-ortega"
  github: "https://www.github.com/AmauryOrtega"
